// <auto-generated />
using Cryptids.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cryptids.Web.Migrations
{
    [DbContext(typeof(CryptidContext))]
    [Migration("20260802051633_AddFieldGuidePlates")]
    partial class AddFieldGuidePlates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cryptids.Web.Models.Cryptid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FirstSighting")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDebunked")
                        .HasColumnType("bit");

                    b.Property<string>("LatinName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Sightings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cryptids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstSighting = 1893,
                            ImageUrl = "/img/cryptids/hodag.webp",
                            IsDebunked = true,
                            LatinName = "Bovine spiritus",
                            Name = "The Hodag",
                            Region = "Rhinelander, Wisconsin",
                            Sightings = 47
                        },
                        new
                        {
                            Id = 2,
                            FirstSighting = 1958,
                            ImageUrl = "/img/cryptids/bigfoot.webp",
                            IsDebunked = false,
                            LatinName = "Gigantopithecus canadensis",
                            Name = "Bigfoot",
                            Region = "Pacific Northwest",
                            Sightings = 1204
                        },
                        new
                        {
                            Id = 3,
                            FirstSighting = 1966,
                            ImageUrl = "/img/cryptids/mothman.webp",
                            IsDebunked = false,
                            LatinName = "Noctua pontiensis",
                            Name = "Mothman",
                            Region = "Point Pleasant, WV",
                            Sightings = 102
                        },
                        new
                        {
                            Id = 4,
                            FirstSighting = 565,
                            ImageUrl = "/img/cryptids/lochness.webp",
                            IsDebunked = false,
                            LatinName = "Nessiteras rhombopteryx",
                            Name = "The Loch Ness Monster",
                            Region = "Loch Ness, Scotland",
                            Sightings = 1131
                        },
                        new
                        {
                            Id = 5,
                            FirstSighting = 1735,
                            ImageUrl = "/img/cryptids/jerseydevil.webp",
                            IsDebunked = false,
                            LatinName = "Diabolus pinorum",
                            Name = "The Jersey Devil",
                            Region = "Pine Barrens, NJ",
                            Sightings = 287
                        },
                        new
                        {
                            Id = 6,
                            FirstSighting = 1995,
                            ImageUrl = "/img/cryptids/chupacabra.webp",
                            IsDebunked = true,
                            LatinName = "Caprivorus portoricensis",
                            Name = "Chupacabra",
                            Region = "Puerto Rico",
                            Sightings = 214
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
